import os
from fpdf import FPDF
from datetime import datetime
from langchain_groq import ChatGroq
from langchain_core.messages import HumanMessage
from dotenv import load_dotenv

load_dotenv()

def get_llm():
    return ChatGroq(
        api_key=os.getenv("GROQ_API_KEY"),
        model_name = "llama-3.1-8b-instant"
    )

def generate_report_content(rag_chain, filename):
    
    questions = {
        "executive_summary": "What is the total net sales, net income, and earnings per share for fiscal year 2023? Summarize the overall financial performance.",
        "key_metrics": "What are the exact figures for: total net sales, gross margin, operating income, net income, earnings per share (basic and diluted), and R&D expenses for 2023?",
        "risk_factors": "List the top 5 risk factors mentioned under Item 1A Risk Factors in this document.",
        "highlights": "What were the major product launches, share repurchase amounts, dividend amounts, and significant business events in fiscal year 2023?",
        "outlook": "What does management say about future guidance, liquidity, capital resources, and expected performance in the next 12 months?"
    }
    
    results = {}
    for key, question in questions.items():
        try:
            answer = rag_chain.invoke(question)
            results[key] = answer
        except:
            results[key] = "Information not available in document."
    
    return results

def create_pdf_report(content, company_name, output_path="report.pdf"):
    """Professional PDF report banata hai"""
    
    pdf = FPDF()
    pdf.add_page()
    
    # Header
    pdf.set_fill_color(10, 10, 15)
    pdf.rect(0, 0, 210, 40, 'F')
    
    pdf.set_font("Helvetica", "B", 24)
    pdf.set_text_color(0, 245, 212)
    pdf.cell(0, 20, "", ln=True)
    pdf.cell(0, 15, f"Financial Analysis Report", ln=True, align="C")
    
    pdf.set_font("Helvetica", "", 12)
    pdf.set_text_color(150, 150, 150)
    pdf.cell(0, 8, f"Company: {company_name}", ln=True, align="C")
    
    pdf.set_font("Helvetica", "", 10)
    pdf.cell(0, 8, 
             f"Generated: {datetime.now().strftime('%B %d, %Y at %I:%M %p')}", 
             ln=True, align="C")
    
    pdf.ln(10)
    
    sections = [
        ("Executive Summary", content.get("executive_summary", "")),
        ("Key Financial Metrics", content.get("key_metrics", "")),
        ("Risk Factors", content.get("risk_factors", "")),
        ("Key Highlights", content.get("highlights", "")),
        ("Future Outlook", content.get("outlook", "")),
    ]
    
    for title, body in sections:
        # Section header
        pdf.set_fill_color(26, 26, 46)
        pdf.set_text_color(0, 245, 212)
        pdf.set_font("Helvetica", "B", 13)
        pdf.set_x(10)
        pdf.cell(190, 10, f"  {title}", ln=True, fill=True)
        pdf.ln(3)
        
        # Section content
        pdf.set_text_color(50, 50, 50)
        pdf.set_font("Helvetica", "", 10)
        
        # Clean text
        clean_body = body.encode('latin-1', 'replace').decode('latin-1')
        pdf.set_x(10)
        pdf.multi_cell(190, 6, clean_body)
        pdf.ln(6)
    
    # Footer
    pdf.set_y(-20)
    pdf.set_font("Helvetica", "I", 8)
    pdf.set_text_color(150, 150, 150)
    pdf.cell(0, 10, 
             "Generated by FinanceAI Assistant | Powered by LLaMA + RAG", 
             align="C")
    
    pdf.output(output_path)
    return output_path